<template>
  <HomepageHeader />
  <div v-if="$store.state.eventLoading" class="text-center my-5">
    <div class="loadingio-spinner-ellipsis-zn4fhzwgb">
      <div class="loadingio-spinner-ellipsis-e2dlnyc4ytc">
        <div class="ldio-8xpx2o6sd04">
          <div></div>
          <div></div>
          <div></div>
          <div></div>
          <div></div>
        </div>
      </div>
    </div>
  </div>
  <!--  -->
  <div v-else class="container">
    <p class="mt-5 mb-4 anounce-title">{{ ann.title }}</p>
    <div class="posting">
      <div class="badge user-badge">
        <img class="profile-img" :src="profile.url" alt="profile.img" />
        <p class="firstname d-inline px-2">{{ creator.firstname }}</p>
        <p class="lastname d-inline px-1">{{ creator.lastname }}</p>
        <p class="time-badge ms-5 ps-3">{{ createAt() }}</p>
      </div>
    </div>
    <hr />
    <!-- Detail -->
    <div class="detail my-4">
      <p>Announcement Details</p>
      <p class="lorem">
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ ann.description }}
      </p>
    </div>
    <hr />
  </div>

  <HPfooter />
</template>

<script>
import HomepageHeader from "../components/HomepageHeader";
import HPfooter from "../components/homepageFooter";
import axios from "axios";
import moment from "moment";

export default {
  setup() {
    return { HomepageHeader, HPfooter };
  },
  data() {
    return {
      creator: {},
      ann: {},
      profile: {},
      loading: true,
    };
  },
  async mounted() {
    const res = await axios.get(`/announcements/${this.$route.params.id}`);
    this.ann = res.data;
    this.creator = res.data.createdBy;
    this.profile = res.data.createdBy.profile_img;
    console.log(this.creator);
    this.$store.state.eventLoading = false;
  },
  methods: {
    createAt() {
      const thisMoment = moment(this.ann.createdAt).format("LL");
      return thisMoment;
    },
  },
};
</script>

<style type="text/css">
@keyframes ldio-8xpx2o6sd04 {
  0% {
    transform: translate(5.699999999999999px, 44.459999999999994px) scale(0);
  }
  25% {
    transform: translate(5.699999999999999px, 44.459999999999994px) scale(0);
  }
  50% {
    transform: translate(5.699999999999999px, 44.459999999999994px) scale(1);
  }
  75% {
    transform: translate(44.459999999999994px, 44.459999999999994px) scale(1);
  }
  100% {
    transform: translate(83.22px, 44.459999999999994px) scale(1);
  }
}
@keyframes ldio-8xpx2o6sd04-r {
  0% {
    transform: translate(83.22px, 44.459999999999994px) scale(1);
  }
  100% {
    transform: translate(83.22px, 44.459999999999994px) scale(0);
  }
}
@keyframes ldio-8xpx2o6sd04-c {
  0% {
    background: #85a2b6;
  }
  25% {
    background: #fdfdfd;
  }
  50% {
    background: #dce4eb;
  }
  75% {
    background: #bbcedd;
  }
  100% {
    background: #85a2b6;
  }
}
.ldio-8xpx2o6sd04 div {
  position: absolute;
  width: 25.08px;
  height: 25.08px;
  border-radius: 50%;
  transform: translate(44.459999999999994px, 44.459999999999994px) scale(1);
  background: #85a2b6;
  animation: ldio-8xpx2o6sd04 5.5555555555555545s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-8xpx2o6sd04 div:nth-child(1) {
  background: #bbcedd;
  transform: translate(83.22px, 44.459999999999994px) scale(1);
  animation: ldio-8xpx2o6sd04-r 1.3888888888888886s infinite cubic-bezier(0, 0.5, 0.5, 1),
    ldio-8xpx2o6sd04-c 5.5555555555555545s infinite step-start;
}
.ldio-8xpx2o6sd04 div:nth-child(2) {
  animation-delay: -1.3888888888888886s;
  background: #85a2b6;
}
.ldio-8xpx2o6sd04 div:nth-child(3) {
  animation-delay: -2.7777777777777772s;
  background: #bbcedd;
}
.ldio-8xpx2o6sd04 div:nth-child(4) {
  animation-delay: -4.166666666666666s;
  background: #dce4eb;
}
.ldio-8xpx2o6sd04 div:nth-child(5) {
  animation-delay: -5.5555555555555545s;
  background: #fdfdfd;
}
.loadingio-spinner-ellipsis-e2dlnyc4ytc {
  width: 114px;
  height: 114px;
  display: inline-block;
  overflow: hidden;
  background: none;
}
.ldio-8xpx2o6sd04 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-8xpx2o6sd04 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>

<style scoped>
.lorem {
  font-family: "THSaraban";
}
.container {
  max-width: 680px;
  width: 100%;
}
.profile-img {
  border-radius: 50%;
  width: 60px;
  height: 60px;
  object-fit: cover;
}
.user-badge {
  font-weight: 400;
  font-size: 21px;
  color: #000000;
  border-radius: 0px;
  font-family: "THSaraban";
  padding: 0px 0px;
}
.user-badge .p {
  margin-top: 2px;
}
.time-badge {
  color: #636468;
  margin-top: -8px;
  margin-left: 47px;
  line-height: 0;
}
.anounce-title {
  font-size: 26px;
}

@media screen and (max-width: 551.98) {
  container {
    margin: 0 24px;
  }
}

@media screen and (max-width: 727.98px) and (min-width: 552px) {
  container {
    margin: 0 24px;
  }
}

@media screen and (max-width: 903.98px) and (min-width: 728px) {
  container {
    margin: 0 48px;
  }
}

@media screen and (max-width: 1079.98px) and (min-width: 904px) {
  container {
    margin: 0 64px;
  }
}
</style>
