<template>
  <HomepageHeader />
  <div v-if="loading" class="text-center">
    <div class="loadingio-spinner-ellipsis-zn4fhzwgb">
      <div class="ldio-yjhkrbku5e">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
  <!--  -->
  <div class="container" v-if="!loading">
    <p class="mt-3 mb-4 anounce-title text-center text-md-start">
      {{ $store.state.newsData.title }}
    </p>
    <div class="posting">
      <div class="badge user-badge">
        <img class="profile-img" :src="crePro.url" alt="profile.img" />
        <p class="firstname d-inline px-2">{{ creator.firstname }}</p>
        <p class="lastname d-inline px-1">{{ creator.lastname }}</p>
        <p class="time-badge">{{ createAt() }}</p>
      </div>
    </div>
    <hr />
    <div class="detail my-4">
      <p>News Details</p>
    </div>
    <p class="lorem">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
      {{ $store.state.newsData.description }}
    </p>
    <hr />
    <div class="mb-5">
      <div class="row">
        <div
          v-for="(image, index) in $store.state.newsData.images"
          :key="index"
          class="mx-0 col-12 col-sm-6"
        >
          <div class="row mb-3 justify-content-center">
            <img
              :src="$store.state.newsData.images[index].url"
              class="col-12 rounded-0 sample-img"
            />
          </div>
        </div>
      </div>
    </div>
  </div>

  <HPfooter />
</template>

<script>
import HomepageHeader from "../components/HomepageHeader";
import HPfooter from "../components/homepageFooter";
import axios from "axios";
import moment from "moment";

export default {
  setup() {
    return {
      HomepageHeader,
      HPfooter,
      creator: {},
      newsDetail: {},
      test: "",
      crePro: "",
    };
  },
  data() {
    return {
      loading: true,
    };
  },
  async mounted() {
    const newsdata = await axios.get(`/news/${this.$route.params.id}`);
    this.$store.state.newsData = newsdata.data;
    this.creator = this.$store.state.newsData.createdBy;
    this.crePro = this.creator.profile_img;
    this.loading = false;

    console.log(this.creator);
    console.log(this.creator);
    console.log(newsdata);
    console.log(this.$store.state.newsData);

    const res = await axios.get("/users/profile");
    this.$store.state.info = res.data;
    this.$store.state.profileimg = res.data.profile_img;
  },
  methods: {
    createAt() {
      const thisMoment = moment(this.$store.state.newsData.createdAt).format("LL");
      return thisMoment;
    },
  },
};
</script>
<style scoped type="text/css">
  .sample-img{
  width: 100%;
  height: 345px;
  object-fit: cover;
  object-position: top;
}
@keyframes ldio-yjhkrbku5e {
0% {
  transform: translate(29.64px, 113.62px) scale(0);
}
25% {
  transform: translate(29.64px, 113.62px) scale(0);
}
50% {
  transform: translate(29.64px, 113.62px) scale(1);
}
75% {
  transform: translate(113.62px, 113.62px) scale(1);
}
100% {
  transform: translate(197.60000000000002px, 113.62px) scale(1);
}
}
@keyframes ldio-yjhkrbku5e-r {
0% {
  transform: translate(197.60000000000002px, 113.62px) scale(1);
}
100% {
  transform: translate(197.60000000000002px, 113.62px) scale(0);
}
}
@keyframes ldio-yjhkrbku5e-c {
0% {
  background: #ffffff;
}
25% {
  background: #ffdbdb;
}
50% {
  background: #ffe7e7;
}
75% {
  background: #fff5f5;
}
100% {
  background: #ffffff;
}
}
.ldio-yjhkrbku5e div {
position: absolute;
width: 19.76px;
height: 19.76px;
border-radius: 50%;
transform: translate(113.62px, 113.62px) scale(1);
background: #ffffff;
animation: ldio-yjhkrbku5e 5.5555555555555545s infinite cubic-bezier(0, 0.5, 0.5, 1);
}
.ldio-yjhkrbku5e div:nth-child(1) {
background: #fff5f5;
transform: translate(197.60000000000002px, 113.62px) scale(1);
animation: ldio-yjhkrbku5e-r 1.3888888888888886s infinite cubic-bezier(0, 0.5, 0.5, 1),
  ldio-yjhkrbku5e-c 5.5555555555555545s infinite step-start;
}
.ldio-yjhkrbku5e div:nth-child(2) {
animation-delay: -1.3888888888888886s;
background: #ffffff;
}
.ldio-yjhkrbku5e div:nth-child(3) {
animation-delay: -2.7777777777777772s;
background: #fff5f5;
}
.ldio-yjhkrbku5e div:nth-child(4) {
animation-delay: -4.166666666666666s;
background: #ffe7e7;
}
.ldio-yjhkrbku5e div:nth-child(5) {
animation-delay: -5.5555555555555545s;
background: #ffdbdb;
}
.loadingio-spinner-ellipsis-zn4fhzwgb {
width: 247px;
height: 247px;
display: inline-block;
overflow: hidden;
background: #ffffff;
}
.ldio-yjhkrbku5e {
width: 100%;
height: 100%;
position: relative;
transform: translateZ(0) scale(1);
backface-visibility: hidden;
transform-origin: 0 0; /* see note above */
}
.ldio-yjhkrbku5e div {
box-sizing: content-box;
}
/* generated by https://loading.io/ */
[v-cloak] {
display: none;
}
</style>

<style scoped>
.sample-img {
  width: 100%;
  height: 345px;
  object-fit: cover;
  object-position: top;
}
.img-act {
  width: 100%;
  object-fit: cover;
  padding: 2% 0%;
}
.lorem {
  font-family: "THSaraban";
}
.container {
  max-width: 680px;
  width: 100%;
}
.profile-img {
  border-radius: 50%;
  width: 60px;
  height: 60px;
  object-fit: cover;
}
.user-badge {
  font-weight: 400;
  font-size: 21px;
  color: #000000;
  border-radius: 0px;
  font-family: "THSaraban";
  padding: 0px 0px;
}
.user-badge .p {
  margin-top: 2px;
}
.time-badge {
  color: #636468;
  margin-top: -8px;
  margin-left: 47px;
  line-height: 0;
}
.anounce-title {
  font-size: 26px;
}

@media screen and (max-width: 551.98) {
  container {
    margin: 0 24px;
  }
}

@media screen and (max-width: 727.98px) and (min-width: 552px) {
  container {
    margin: 0 24px;
  }
}

@media screen and (max-width: 903.98px) and (min-width: 728px) {
  container {
    margin: 0 48px;
  }
}

@media screen and (max-width: 1079.98px) and (min-width: 904px) {
  container {
    margin: 0 64px;
  }
}
</style>
